import { createFileRoute } from "@tanstack/react-router";
import type {} from "@tanstack/react-start";

// ADVAQ Production Domain
const BASE_URL = "https://advaq.com";

interface SitemapEntry {
  path: string;
  changefreq?: "always" | "hourly" | "daily" | "weekly" | "monthly" | "yearly" | "never";
  priority?: string;
}

export const Route = createFileRoute("/sitemap.xml")({
  server: {
    handlers: {
      GET: async () => {
        const entries: SitemapEntry[] = [
          { path: "/", changefreq: "weekly", priority: "1.0" },
          { path: "/about", changefreq: "monthly", priority: "0.8" },
          { path: "/uk-services", changefreq: "monthly", priority: "0.9" },
          { path: "/us-services", changefreq: "monthly", priority: "0.9" },
          { path: "/uae-services", changefreq: "monthly", priority: "0.9" },
          { path: "/pakistan-services", changefreq: "monthly", priority: "0.9" },
          { path: "/legal-contract-drafting", changefreq: "monthly", priority: "0.9" },
          { path: "/blog", changefreq: "weekly", priority: "0.8" },
          { path: "/blog/can-non-uk-resident-register-company-uk", changefreq: "monthly", priority: "0.8" },
          { path: "/blog/uk-ltd-vs-sole-trader-non-resident", changefreq: "monthly", priority: "0.8" },
          { path: "/blog/uk-company-formation-documents-required", changefreq: "monthly", priority: "0.8" },
          { path: "/blog/how-long-to-register-uk-company-house", changefreq: "monthly", priority: "0.8" },
          { path: "/blog/registered-office-address-vs-service-address-uk", changefreq: "monthly", priority: "0.8" },
          { path: "/blog/open-uk-business-bank-account-non-resident", changefreq: "monthly", priority: "0.8" },
          { path: "/blog/best-bank-account-for-uk-ltd-non-resident", changefreq: "monthly", priority: "0.8" },
          { path: "/blog/uk-business-bank-account-overseas-director", changefreq: "monthly", priority: "0.8" },
          { path: "/blog/do-non-uk-residents-pay-uk-tax-ltd-company", changefreq: "monthly", priority: "0.8" },
          { path: "/blog/register-uk-corporation-tax-non-resident", changefreq: "monthly", priority: "0.8" },
          { path: "/blog/uk-vat-registration-non-resident-threshold", changefreq: "monthly", priority: "0.8" },
          { path: "/blog/uk-confirmation-statement-cs01-non-resident", changefreq: "monthly", priority: "0.8" },
          { path: "/blog/file-annual-accounts-uk-ltd-non-resident", changefreq: "monthly", priority: "0.8" },
          { path: "/blog/uk-paye-payroll-non-resident-director", changefreq: "monthly", priority: "0.8" },
          { path: "/blog/uk-ltd-dividend-planning-non-resident", changefreq: "monthly", priority: "0.8" },
          { path: "/blog/uk-self-assessment-non-resident-director", changefreq: "monthly", priority: "0.8" },
          { path: "/blog/uk-ltd-bookkeeping-non-resident", changefreq: "monthly", priority: "0.8" },
          { path: "/blog/register-trademark-ukipo-guide", changefreq: "monthly", priority: "0.8" },
          { path: "/blog/is-company-secretary-mandatory-uk", changefreq: "monthly", priority: "0.8" },
          { path: "/blog/how-to-dissolve-uk-limited-company-ds01", changefreq: "monthly", priority: "0.8" },
          { path: "/blog/can-non-us-resident-form-us-llc", changefreq: "monthly", priority: "0.8" },
          { path: "/blog/wyoming-vs-delaware-llc-non-resident", changefreq: "monthly", priority: "0.8" },
          { path: "/blog/single-member-vs-multi-member-llc-non-resident", changefreq: "monthly", priority: "0.8" },
          { path: "/blog/us-llc-formation-documents-required", changefreq: "monthly", priority: "0.8" },
          { path: "/blog/registered-agent-vs-virtual-address-us-llc", changefreq: "monthly", priority: "0.8" },
          { path: "/blog/how-to-get-ein-without-ssn-non-us-resident", changefreq: "monthly", priority: "0.8" },
          { path: "/blog/best-us-business-bank-account-non-resident", changefreq: "monthly", priority: "0.8" },
          { path: "/blog/how-to-get-itin-non-us-resident", changefreq: "monthly", priority: "0.8" },
          { path: "/blog/connect-stripe-to-us-llc-foreign-owner", changefreq: "monthly", priority: "0.8" },
          { path: "/blog/transfer-money-from-us-llc-bank-account-foreign-country", changefreq: "monthly", priority: "0.8" },
          { path: "/blog/form-5472-non-resident-single-member-llc", changefreq: "monthly", priority: "0.8" },
          { path: "/blog/form-5472-late-filing-penalty-irs", changefreq: "monthly", priority: "0.8" },
          { path: "/blog/us-sales-tax-economic-nexus-foreign-seller", changefreq: "monthly", priority: "0.8" },
          { path: "/blog/do-non-us-residents-pay-us-income-tax-llc", changefreq: "monthly", priority: "0.8" },
          { path: "/blog/us-llc-state-annual-report-filing-guide", changefreq: "monthly", priority: "0.8" },
          { path: "/blog/uspto-trademark-registration-guide-foreign-applicant", changefreq: "monthly", priority: "0.8" },
          { path: "/blog/beneficial-ownership-information-boi-reporting-us-llc", changefreq: "monthly", priority: "0.8" },
          { path: "/blog/us-physical-business-address-vs-mail-forwarding", changefreq: "monthly", priority: "0.8" },
          { path: "/blog/change-registered-agent-wyoming-delaware", changefreq: "monthly", priority: "0.8" },
          { path: "/blog/how-to-dissolve-us-llc-foreign-owner", changefreq: "monthly", priority: "0.8" },
          { path: "/blog/dubai-freezone-vs-mainland-non-resident", changefreq: "monthly", priority: "0.8" },
          { path: "/blog/cheapest-freezone-in-dubai-for-it-company", changefreq: "monthly", priority: "0.8" },
          { path: "/blog/register-dubai-mainland-company-without-local-sponsor", changefreq: "monthly", priority: "0.8" },
          { path: "/blog/ifza-vs-meydan-vs-shams-freezone-comparison", changefreq: "monthly", priority: "0.8" },
          { path: "/blog/flexi-desk-vs-office-space-uae-freezone", changefreq: "monthly", priority: "0.8" },
          { path: "/blog/how-to-get-uae-investor-visa-company-setup", changefreq: "monthly", priority: "0.8" },
          { path: "/blog/uae-golden-visa-for-tech-founders-eligibility", changefreq: "monthly", priority: "0.8" },
          { path: "/blog/sponsor-family-in-dubai-investor-visa", changefreq: "monthly", priority: "0.8" },
          { path: "/blog/uae-medical-test-emirates-id-biometrics-process", changefreq: "monthly", priority: "0.8" },
          { path: "/blog/work-remotely-uae-freezone-visa-rules", changefreq: "monthly", priority: "0.8" },
          { path: "/blog/uae-corporate-tax-9-percent-freezone-rules", changefreq: "monthly", priority: "0.8" },
          { path: "/blog/open-corporate-bank-account-in-dubai-freezone", changefreq: "monthly", priority: "0.8" },
          { path: "/blog/uae-vat-registration-threshold-5-percent", changefreq: "monthly", priority: "0.8" },
          { path: "/blog/dubai-corporate-bank-account-compliance-approval", changefreq: "monthly", priority: "0.8" },
          { path: "/blog/wio-bank-vs-traditional-uae-business-account", changefreq: "monthly", priority: "0.8" },
          { path: "/blog/mofa-attestation-uae-foreign-documents-guide", changefreq: "monthly", priority: "0.8" },
          { path: "/blog/register-trademark-uae-ministry-of-economy", changefreq: "monthly", priority: "0.8" },
          { path: "/blog/uae-economic-substance-regulations-esr-guide", changefreq: "monthly", priority: "0.8" },
          { path: "/blog/uae-ultimate-beneficial-owner-ubo-declaration", changefreq: "monthly", priority: "0.8" },
          { path: "/blog/how-to-liquidate-uae-freezone-company-license", changefreq: "monthly", priority: "0.8" },
          { path: "/blog/single-member-company-vs-private-limited-secp-pakistan", changefreq: "monthly", priority: "0.8" },
          { path: "/blog/how-to-register-company-in-secp-online-pakistan", changefreq: "monthly", priority: "0.8" },
          { path: "/blog/pvt-ltd-vs-sole-proprietorship-vs-aop-pakistan", changefreq: "monthly", priority: "0.8" },
          { path: "/blog/secp-authorized-capital-paid-up-capital-rules", changefreq: "monthly", priority: "0.8" },
          { path: "/blog/foreign-direct-investment-secp-company-pakistan", changefreq: "monthly", priority: "0.8" },
          { path: "/blog/pseb-registration-benefits-tax-credit-it-export", changefreq: "monthly", priority: "0.8" },
          { path: "/blog/sbp-form-r-foreign-remittance-it-exporter-pakistan", changefreq: "monthly", priority: "0.8" },
          { path: "/blog/exporters-special-fcva-account-sbp-it-freelancers", changefreq: "monthly", priority: "0.8" },
          { path: "/blog/open-company-business-bank-account-pakistan", changefreq: "monthly", priority: "0.8" },
          { path: "/blog/chamber-of-commerce-registration-pakistan-guide", changefreq: "monthly", priority: "0.8" },
          { path: "/blog/file-for-income-tax-return-iris-pakistan-active-taxpayer", changefreq: "monthly", priority: "0.8" },
          { path: "/blog/sales-tax-on-services-pra-srb-fbr-it-companies", changefreq: "monthly", priority: "0.8" },
          { path: "/blog/how-to-register-ntn-online-for-pakistan", changefreq: "monthly", priority: "0.8" },
          { path: "/blog/withholding-tax-rates-section-152-secp-company", changefreq: "monthly", priority: "0.8" },
          { path: "/blog/secp-annual-compliance-form-a-form-29-deadline", changefreq: "monthly", priority: "0.8" },
          { path: "/blog/register-trademark-ipo-pakistan-guide", changefreq: "monthly", priority: "0.8" },
          { path: "/blog/weboc-customs-registration-guide-pakistan", changefreq: "monthly", priority: "0.8" },
          { path: "/blog/filer-vs-non-filer-pakistan-benefits-penalties", changefreq: "monthly", priority: "0.8" },
          { path: "/blog/tax-exemption-software-house-it-exporter-pakistan", changefreq: "monthly", priority: "0.8" },
          { path: "/blog/how-to-winding-up-company-secp-easy-exit-scheme", changefreq: "monthly", priority: "0.8" },
          { path: "/blog/master-service-agreement-vs-statement-of-work", changefreq: "monthly", priority: "0.8" },
          { path: "/blog/software-development-agreement-checklist", changefreq: "monthly", priority: "0.8" },
          { path: "/blog/fixed-price-vs-hourly-retainer-agreement-agency", changefreq: "monthly", priority: "0.8" },
          { path: "/blog/prevent-scope-creep-contract-clauses-agency", changefreq: "monthly", priority: "0.8" },
          { path: "/blog/service-level-agreement-sla-guide-saas", changefreq: "monthly", priority: "0.8" },
          { path: "/blog/ip-assignment-agreement-software-development-ownership", changefreq: "monthly", priority: "0.8" },
          { path: "/blog/one-way-nda-vs-mutual-nda-difference", changefreq: "monthly", priority: "0.8" },
          { path: "/blog/enforcing-nda-contract-international-clients", changefreq: "monthly", priority: "0.8" },
          { path: "/blog/moral-rights-waiver-copyright-assignment-contract", changefreq: "monthly", priority: "0.8" },
          { path: "/blog/employee-confidentiality-agreement-tech-company", changefreq: "monthly", priority: "0.8" },
          { path: "/blog/independent-contractor-vs-employee-misclassification-risk", changefreq: "monthly", priority: "0.8" },
          { path: "/blog/contracting-remote-freelancers-overseas-legally", changefreq: "monthly", priority: "0.8" },
          { path: "/blog/non-compete-non-solicitation-clauses-freelancer", changefreq: "monthly", priority: "0.8" },
          { path: "/blog/tech-company-employment-contract-drafting-guide", changefreq: "monthly", priority: "0.8" },
          { path: "/blog/kill-fee-clauses-freelance-contract-termination", changefreq: "monthly", priority: "0.8" },
          { path: "/blog/terms-of-service-checklist-saas-website", changefreq: "monthly", priority: "0.8" },
          { path: "/blog/gdpr-privacy-policy-requirements-saas-website", changefreq: "monthly", priority: "0.8" },
          { path: "/blog/data-processing-agreement-dpa-gdpr-requirements", changefreq: "monthly", priority: "0.8" },
          { path: "/blog/limitation-of-liability-clause-agency-contract", changefreq: "monthly", priority: "0.8" },
          { path: "/blog/choice-of-law-dispute-resolution-cross-border-contracts", changefreq: "monthly", priority: "0.8" },
          { path: "/calculators", changefreq: "weekly", priority: "0.9" },
          { path: "/calculators/uk", changefreq: "weekly", priority: "0.8" },
          { path: "/calculators/usa", changefreq: "weekly", priority: "0.8" },
          { path: "/calculators/uae", changefreq: "weekly", priority: "0.8" },
          { path: "/calculators/pakistan", changefreq: "weekly", priority: "0.8" },
          { path: "/calculators/us-cost", changefreq: "monthly", priority: "0.8" },
          { path: "/calculators/us-tax-eligibility", changefreq: "monthly", priority: "0.8" },
          { path: "/calculators/us-penalty-risk", changefreq: "monthly", priority: "0.8" },
          { path: "/calculators/us-sales-tax", changefreq: "monthly", priority: "0.8" },
          { path: "/calculators/us-bank-approval", changefreq: "monthly", priority: "0.8" },
          { path: "/calculators/us-llc-vs-c-corp", changefreq: "monthly", priority: "0.8" },
          { path: "/calculators/us-trademark-cost", changefreq: "monthly", priority: "0.8" },
          { path: "/calculators/uk-tax", changefreq: "monthly", priority: "0.8" },
          { path: "/calculators/uk-sole-trader-vs-ltd", changefreq: "monthly", priority: "0.8" },
          { path: "/calculators/uk-vat", changefreq: "monthly", priority: "0.8" },
          { path: "/calculators/uk-setup-cost", changefreq: "monthly", priority: "0.8" },
          { path: "/calculators/uk-penalty-risk", changefreq: "monthly", priority: "0.8" },
          { path: "/calculators/uk-bank-approval", changefreq: "monthly", priority: "0.8" },
          { path: "/calculators/uae-freezone", changefreq: "monthly", priority: "0.8" },
          { path: "/calculators/uae-tax", changefreq: "monthly", priority: "0.8" },
          { path: "/calculators/uae-vat", changefreq: "monthly", priority: "0.8" },
          { path: "/calculators/uae-visa-cost", changefreq: "monthly", priority: "0.8" },
          { path: "/calculators/uae-bank-approval", changefreq: "monthly", priority: "0.8" },
          { path: "/calculators/uae-esr-ubo", changefreq: "monthly", priority: "0.8" },
          { path: "/calculators/pakistan-tax", changefreq: "monthly", priority: "0.8" },
          { path: "/calculators/pakistan-it-export", changefreq: "monthly", priority: "0.8" },
          { path: "/calculators/pakistan-secp-cost", changefreq: "monthly", priority: "0.8" },
          { path: "/calculators/pakistan-fbr-salary-tax", changefreq: "monthly", priority: "0.8" },
          { path: "/calculators/pakistan-sales-tax", changefreq: "monthly", priority: "0.8" },
          { path: "/calculators/pakistan-secp-penalty", changefreq: "monthly", priority: "0.8" },
          { path: "/contact", changefreq: "monthly", priority: "0.7" },
        ];

        const urls = entries.map((e) =>
          [
            `  <url>`,
            `    <loc>${BASE_URL}${e.path}</loc>`,
            e.changefreq ? `    <changefreq>${e.changefreq}</changefreq>` : null,
            e.priority ? `    <priority>${e.priority}</priority>` : null,
            `  </url>`,
          ]
            .filter(Boolean)
            .join("\n"),
        );

        const xml = [
          `<?xml version="1.0" encoding="UTF-8"?>`,
          `<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">`,
          ...urls,
          `</urlset>`,
        ].join("\n");

        return new Response(xml, {
          headers: {
            "Content-Type": "application/xml",
            "Cache-Control": "public, max-age=3600",
          },
        });
      },
    },
  },
});
