import { createFileRoute, Link } from "@tanstack/react-router";
import { useState } from "react";
import {
  ArrowRight,
  Check,
  CheckCircle,
  ChevronDown,
  Shield,
  Calculator,
  CalendarClock,
  DollarSign,
  FileCheck,
  BadgeAlert,
  AlertTriangle,
} from "lucide-react";
import { Reveal } from "@/lib/reveal";
import { SectionLabel } from "@/components/site/SectionLabel";

const faqs = [
  {
    q: "What is Withholding Tax (WHT) Compliance in Pakistan?",
    a: "Withholding tax compliance is the statutory obligation to deduct income or sales tax at the source when making certain payments (like salaries, supplies, rent, or services), depositing the tax with FBR via PSID, and filing a periodic statement of those deductions.",
  },
  {
    q: "Who is required to act as a withholding agent?",
    a: "Companies, registered AOPs, non-profit organizations, and large businesses are designated as withholding agents by FBR. They are legally bound to deduct tax while making payments to vendors, employees, or landlords.",
  },
  {
    q: "How frequently must withholding tax statements be filed?",
    a: "Currently, FBR requires withholding agents to file withholding statements either monthly (under Section 165 of the Income Tax Ordinance) or bi-annually, depending on specific regulatory updates, but generally monthly compliance is the standard for smooth operations.",
  },
  {
    q: "What happens if we fail to deduct withholding tax?",
    a: "If a withholding agent fails to deduct tax, FBR can disallow that specific expense when assessing your annual tax return. Moreover, you may be held personally liable for the uncollected tax amount along with default surcharges and penalties.",
  },
  {
    q: "What is a CPR (Computerized Payment Receipt)?",
    a: "A CPR is the official receipt generated by the bank or FBR system once a withholding tax PSID is paid. It acts as the legal proof of tax deposited in the national treasury.",
  },
  {
    q: "Do I have to issue withholding tax certificates to my vendors?",
    a: "Yes, you must provide your vendors and employees with a withholding tax certificate (under Section 164) generated through the FBR portal. This allows them to claim credit for the tax deducted.",
  },
  {
    q: "How do the withholding tax rates vary?",
    a: "Rates vary widely based on the type of payment (salary, goods, services, execution of contracts, rent) and the Active Taxpayer status of the recipient. Non-ATL recipients are subjected to 100% higher tax rates.",
  },
  {
    q: "How can ADVAQ help with our withholding taxes?",
    a: "We act as your outsourced tax department. We calculate the exact tax to be deducted, generate the PSIDs on time, file your monthly/bi-annual statements, and issue certificates to your vendors—all for a fixed monthly fee.",
  },
  {
    q: "Can we correct a mistake if tax was deposited under the wrong section?",
    a: "Yes, CPR corrections are possible but they require a formal application to the Commissioner Inland Revenue. We handle such correction applications on your behalf to ensure proper adjustment.",
  },
  {
    q: "Is withholding tax compliance required if we only pay salaries?",
    a: "Yes. If any of your employees fall within the taxable income bracket, you must deduct tax from their salary under Section 149, deposit it via CPR, and file the related statements.",
  },
];

const faqSchema = {
  "@context": "https://schema.org",
  "@type": "FAQPage",
  mainEntity: faqs.map((f) => ({
    "@type": "Question",
    name: f.q,
    acceptedAnswer: { "@type": "Answer", text: f.a },
  })),
};

const serviceSchema = {
  "@context": "https://schema.org",
  "@type": "Service",
  serviceType: "Withholding Tax Compliance",
  provider: { "@type": "Organization", name: "ADVAQ" },
  name: "Withholding Tax Compliance in Pakistan",
  description:
    "End-to-end withholding tax compliance, PSID generation, CPR handling, and monthly statement filings for companies and withholding agents in Pakistan.",
  areaServed: "Pakistan",
  url: "https://[yourdomain.com]/pakistan-services/withholding-compliance",
  offers: {
    "@type": "Offer",
    price: "49.00",
    priceCurrency: "USD",
    description: "Monthly Withholding Tax Compliance fee.",
  },
};

export const Route = createFileRoute("/pakistan-services/withholding-compliance")({
  head: () => ({
    meta: [
      { title: "Withholding Tax Compliance Pakistan | ADVAQ" },
      {
        name: "description",
        content:
          "Ensure FBR withholding tax compliance. We manage monthly tax deductions, PSID generation, CPRs, and statement filings for your company.",
      },
      {
        name: "keywords",
        content:
          "withholding tax pakistan, withholding tax statement, wht compliance, fbr monthly statements, cpr generation, section 149 salary tax",
      },
      {
        property: "og:title",
        content: "Withholding Tax Compliance Pakistan | ADVAQ",
      },
      {
        property: "og:description",
        content:
          "Ensure FBR withholding tax compliance. We manage monthly tax deductions, PSID generation, CPRs, and statement filings for your company.",
      },
      { property: "og:url", content: "/pakistan-services/withholding-compliance" },
    ],
    links: [{ rel: "canonical", href: "https://[yourdomain.com]/pakistan-services/withholding-compliance" }],
    scripts: [
      { type: "application/ld+json", children: JSON.stringify(faqSchema) },
      { type: "application/ld+json", children: JSON.stringify(serviceSchema) },
    ],
  }),
  component: WithholdingCompliance,
});

/* ---------- SECTION 1: HERO ---------- */
function Hero() {
  return (
    <section className="relative bg-navy-950 pt-36 pb-24 overflow-hidden min-h-[80vh] flex items-center">
      <div className="absolute inset-0 grid-pattern opacity-100" />
      <div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-[600px] h-[600px] bg-gold-500/6 blur-[120px] rounded-full pointer-events-none" />

      <div className="relative max-w-5xl mx-auto px-6 text-center">
        <Reveal>
          <p className="text-gold-500 uppercase text-xs font-semibold tracking-[0.15em] inline-flex items-center gap-2">
            🇵🇰 MONTHLY FBR COMPLIANCE
          </p>
          <h1 className="font-serif text-white text-[38px] md:text-[60px] mt-5 leading-[1.1] max-w-4xl mx-auto">
            Withholding Tax
            <br />
            Compliance
          </h1>
          <p className="mt-6 text-navy-200 text-[18px] max-w-2xl mx-auto leading-[1.75]">
            Outsource your monthly withholding tax operations. We calculate deductions, generate PSIDs, issue vendor certificates, and file FBR statements to keep you penalty-free.
          </p>
          <div className="mt-10 flex flex-wrap gap-4 justify-center">
            <Link to="/contact" className="btn-gold rounded-none uppercase tracking-widest">
              Get Started Now
            </Link>
            <a
              href="https://wa.me/923000925335"
              target="_blank"
              rel="noopener noreferrer"
              className="btn-outline-light rounded-none uppercase tracking-widest"
            >
              Ask on WhatsApp
            </a>
          </div>
          <div className="mt-12 flex flex-wrap justify-center gap-x-8 gap-y-3 text-[13px] text-navy-200">
            <span className="inline-flex items-center gap-2">
              <Check size={16} className="text-gold-500" /> Accurate Deductions
            </span>
            <span className="inline-flex items-center gap-2">
              <Check size={16} className="text-gold-500" /> PSID & CPR Handling
            </span>
            <span className="inline-flex items-center gap-2">
              <Check size={16} className="text-gold-500" /> Monthly Filings
            </span>
            <span className="inline-flex items-center gap-2">
              <Check size={16} className="text-gold-500" /> Complete Audit Trail
            </span>
          </div>
        </Reveal>
      </div>
    </section>
  );
}

/* ---------- SECTION 2: WHAT IS IT ---------- */
function ServiceOverview() {
  return (
    <section className="bg-white py-24">
      <div className="max-w-6xl mx-auto px-6">
        <div className="grid lg:grid-cols-12 gap-12 items-center">
          <div className="lg:col-span-7">
            <Reveal>
              <SectionLabel>THE OBLIGATION</SectionLabel>
              <h2 className="font-serif text-[32px] md:text-[44px] text-dark-text mt-4">
                What is Withholding Compliance?
              </h2>
              <p className="mt-6 text-gray-700 text-[16px] leading-[1.8]">
                As a corporate entity, FBR appoints you as a "Withholding Agent." This means before paying salaries, supplier invoices, or rent, you must legally deduct a percentage of that payment as tax on behalf of the government.
              </p>
              <p className="mt-4 text-gray-700 text-[16px] leading-[1.8]">
                Withholding compliance involves applying the correct tax rates (which differ for active and non-active recipients), depositing the tax into the state treasury, and filing detailed monthly statements declaring those deductions on the IRIS portal.
              </p>
            </Reveal>
          </div>
          <div className="lg:col-span-5">
            <Reveal>
              <div className="bg-navy-950 p-8 rounded-2xl border border-white/10 relative">
                <div className="absolute top-4 right-4 text-gold-500/20">
                  <Calculator size={80} />
                </div>
                <h3 className="font-serif text-xl text-white mb-4">Why Accuracy Matters</h3>
                <ul className="space-y-4 text-sm text-navy-200">
                  <li className="flex items-start gap-2.5">
                    <CheckCircle size={16} className="text-gold-500 mt-0.5 shrink-0" />
                    <span><strong className="font-semibold">Expense Disallowance:</strong> FBR can reject your corporate expenses if no tax was withheld, inflating your final tax bill.</span>
                  </li>
                  <li className="flex items-start gap-2.5">
                    <CheckCircle size={16} className="text-gold-500 mt-0.5 shrink-0" />
                    <span><strong className="font-semibold">Double Liability:</strong> You become personally liable to pay the tax you forgot to deduct from your vendor.</span>
                  </li>
                  <li className="flex items-start gap-2.5">
                    <CheckCircle size={16} className="text-gold-500 mt-0.5 shrink-0" />
                    <span><strong className="font-semibold">Default Surcharges:</strong> Late deposits accumulate default surcharges and harsh penalties.</span>
                  </li>
                </ul>
              </div>
            </Reveal>
          </div>
        </div>
      </div>
    </section>
  );
}

/* ---------- SECTION 3: THE DANGER ---------- */
function TheDanger() {
  return (
    <section className="bg-off-white py-24 border-y border-border">
      <div className="max-w-6xl mx-auto px-6">
        <Reveal className="text-center">
          <SectionLabel center>THE RISK</SectionLabel>
          <h2 className="font-serif text-[32px] md:text-[44px] text-dark-text mt-4">
            The Danger of Mismanagement
          </h2>
          <p className="text-gray-600 text-[17px] max-w-2xl mx-auto mt-4">
            Improper withholding tax management is the number one cause of FBR tax audits.
          </p>
        </Reveal>

        <div className="grid md:grid-cols-3 gap-8 mt-16">
          <Reveal>
            <div className="bg-white border border-gray-200 rounded-[20px] p-6 sm:p-8 shadow-sm hover:shadow-xl hover:-translate-y-1.5 hover:border-red-400 transition-all duration-300 flex flex-col justify-between h-full group">
              <div>
                <div className="w-11 h-11 rounded-xl bg-red-50 text-red-600 border border-red-200 flex items-center justify-center mb-4 group-hover:scale-105 transition-transform">
                  <AlertTriangle size={22} />
                </div>
                <h3 className="font-sans text-lg font-bold text-navy-950">
                  FBR Audits
                </h3>
                <p className="text-gray-600 text-[13.5px] leading-relaxed mt-2">
                  Discrepancies in withholding statements automatically trigger FBR system audits under Section 161/205. The tax authorities can scrutinize years of your payment records.
                </p>
              </div>
            </div>
          </Reveal>

          <Reveal>
            <div className="bg-white border border-gray-200 rounded-[20px] p-6 sm:p-8 shadow-sm hover:shadow-xl hover:-translate-y-1.5 hover:border-red-400 transition-all duration-300 flex flex-col justify-between h-full group">
              <div>
                <div className="w-11 h-11 rounded-xl bg-red-50 text-red-600 border border-red-200 flex items-center justify-center mb-4 group-hover:scale-105 transition-transform">
                  <AlertTriangle size={22} />
                </div>
                <h3 className="font-sans text-lg font-bold text-navy-950">
                  Vendor Disputes
                </h3>
                <p className="text-gray-600 text-[13.5px] leading-relaxed mt-2">
                  Deducting the wrong rates or failing to issue CPR certificates angers vendors who need those certificates to claim credit for their own tax returns.
                </p>
              </div>
            </div>
          </Reveal>

          <Reveal>
            <div className="bg-white border border-gray-200 rounded-[20px] p-6 sm:p-8 shadow-sm hover:shadow-xl hover:-translate-y-1.5 hover:border-red-400 transition-all duration-300 flex flex-col justify-between h-full group">
              <div>
                <div className="w-11 h-11 rounded-xl bg-red-50 text-red-600 border border-red-200 flex items-center justify-center mb-4 group-hover:scale-105 transition-transform">
                  <AlertTriangle size={22} />
                </div>
                <h3 className="font-sans text-lg font-bold text-navy-950">
                  Hefty Penalties
                </h3>
                <p className="text-gray-600 text-[13.5px] leading-relaxed mt-2">
                  Under-withholding leads to massive default surcharges. FBR treats uncollected withholding taxes strictly and levies fines that compound daily.
                </p>
              </div>
            </div>
          </Reveal>
        </div>
      </div>
    </section>
  );
}

/* ---------- SECTION 4: WHAT IS INCLUDED ---------- */
function WhatIsIncluded() {
  const inclusions = [
    {
      title: "Rate Application",
      desc: "We verify the active/inactive status of your payees and apply the correct statutory tax rates before you pay them.",
    },
    {
      title: "PSID Generation",
      desc: "Creating accurate FBR challans (PSIDs) so you can seamlessly deposit the withheld tax through online banking.",
    },
    {
      title: "CPR Management",
      desc: "Archiving and managing all your Computerized Payment Receipts for a solid audit trail.",
    },
    {
      title: "Statement Filing",
      desc: "Preparing and filing your periodic withholding tax statements on the FBR IRIS portal accurately and on time.",
    },
    {
      title: "Certificate Issuance",
      desc: "Generating and sharing the required withholding tax certificates for your vendors and employees.",
    },
    {
      title: "Notice Handling",
      desc: "Proactively addressing and resolving any systemic anomalies or FBR notices regarding withholding tax defaults.",
    },
  ];

  return (
    <section className="bg-white py-24">
      <div className="max-w-6xl mx-auto px-6">
        <Reveal className="text-center mb-16">
          <SectionLabel center>OUR SOLUTION</SectionLabel>
          <h2 className="font-serif text-[32px] md:text-[44px] text-dark-text mt-4">
            Comprehensive Management
          </h2>
          <p className="text-gray-600 text-[17px] max-w-2xl mx-auto mt-4">
            We handle the complexity of rates, challans, and portal statements.
          </p>
        </Reveal>

        <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-8">
          {inclusions.map((inc) => (
            <Reveal key={inc.title}>
              <div className="border border-border p-8 rounded-xl bg-white hover:border-gold-500/40 hover:-translate-y-1.5 transition-all duration-300">
                <FileCheck className="text-gold-500 mb-4" size={24} />
                <h3 className="font-sans text-[18px] font-semibold text-dark-text">{inc.title}</h3>
                <p className="mt-2 text-sm text-gray-600 leading-relaxed">{inc.desc}</p>
              </div>
            </Reveal>
          ))}
        </div>
      </div>
    </section>
  );
}

/* ---------- SECTION 5: PRICING ---------- */
function Pricing() {
  return (
    <section className="bg-off-white py-24 border-y border-border">
      <div className="max-w-5xl mx-auto px-6">
        <Reveal className="text-center mb-12">
          <SectionLabel center>TRANSPARENT PRICING</SectionLabel>
          <h2 className="font-serif text-[32px] md:text-[44px] text-dark-text mt-4">
            Monthly Compliance Plans
          </h2>
        </Reveal>

        <div className="grid md:grid-cols-1 gap-8 max-w-xl mx-auto">
          <Reveal>
            <div className="bg-white border-[2px] border-gold-500 p-8 rounded-2xl shadow-[0_8px_30px_rgba(201,168,76,0.1)] flex flex-col justify-between h-full relative">
              <span className="absolute -top-3.5 left-1/2 -translate-x-1/2 bg-gold-500 text-navy-900 text-[10px] font-bold uppercase tracking-widest px-4 py-1 rounded-full">
                MONTHLY RETAINER
              </span>
              <div className="text-center">
                <h3 className="font-sans text-2xl font-bold text-dark-text mt-2">Compliance Plan</h3>
                <div className="mt-4 flex items-baseline justify-center gap-2">
                  <span className="font-serif text-4xl text-navy-900">Rs. 5,000</span>
                  <span className="text-xs text-gray-500">/ month</span>
                </div>
                <p className="text-sm text-gray-500 mt-2">Complete withholding tax outsourcing.</p>
                <div className="h-px bg-border my-6" />
                <ul className="space-y-3 text-sm text-gray-700 text-left">
                  <li className="flex items-center gap-2"><Check size={16} className="text-gold-500" /> PSID Generation</li>
                  <li className="flex items-center gap-2"><Check size={16} className="text-gold-500" /> Rate Verifications</li>
                  <li className="flex items-center gap-2"><Check size={16} className="text-gold-500" /> WHT Statements Filing</li>
                  <li className="flex items-center gap-2"><Check size={16} className="text-gold-500" /> Certificate Generation</li>
                </ul>
              </div>
              <Link
                to="/contact"
                className="btn-gold rounded-none uppercase tracking-widest mt-8 w-full text-center"
              >
                Hire Us Now
              </Link>
            </div>
          </Reveal>
        </div>
      </div>
    </section>
  );
}

/* ---------- SECTION 6: PROCESS ---------- */
function ProcessSteps() {
  const steps = [
    {
      title: "Data Handover",
      desc: "Share your monthly payment ledger (salaries, vendors, rent) with our team.",
    },
    {
      title: "Calculation",
      desc: "We verify ATL statuses and calculate exact deduction amounts for each party.",
    },
    {
      title: "PSID & Payment",
      desc: "We generate FBR PSIDs; you pay them via online banking, which produces the CPRs.",
    },
    {
      title: "Portal Filing",
      desc: "We compile all CPRs and file the statutory statement on the FBR IRIS portal.",
    },
    {
      title: "Certificates",
      desc: "We issue formal withholding tax certificates to your employees and vendors.",
    },
  ];

  return (
    <section className="bg-white py-24">
      <div className="max-w-6xl mx-auto px-6">
        <Reveal className="text-center mb-16">
          <SectionLabel center>OUR WORKFLOW</SectionLabel>
          <h2 className="font-serif text-[32px] md:text-[44px] text-dark-text mt-4">
            The Monthly Routine
          </h2>
          <p className="text-gray-600 text-[17px] max-w-2xl mx-auto mt-4">
            Structured processes to ensure you never miss a deadline.
          </p>
        </Reveal>

        <div className="grid md:grid-cols-5 gap-8 mt-12">
          {steps.map((st, idx) => (
            <Reveal key={st.title}>
              <div className="text-center px-2">
                <div className="w-16 h-16 rounded-full border border-gold-500 flex items-center justify-center mx-auto mb-4 bg-gold-500/5">
                  <span className="font-serif text-2xl text-gold-500">{idx + 1}</span>
                </div>
                <h3 className="font-sans font-semibold text-lg text-dark-text mt-2">{st.title}</h3>
                <p className="mt-2 text-xs text-gray-600 leading-relaxed">{st.desc}</p>
              </div>
            </Reveal>
          ))}
        </div>
      </div>
    </section>
  );
}

/* ---------- SECTION 8: FAQ ---------- */
function FAQAccordionItem({ q, a }: { q: string; a: string }) {
  const [isOpen, setIsOpen] = useState(false);
  return (
    <div className="border-b border-white/10 last:border-0">
      <button
        onClick={() => setIsOpen(!isOpen)}
        className="flex justify-between items-center w-full py-6 text-left text-lg font-medium text-white hover:text-gold-500 transition-colors focus:outline-none"
      >
        <span className="pr-6">{q}</span>
        <ChevronDown
          size={20}
          className={`text-gold-500 shrink-0 transform transition-transform duration-300 ${
            isOpen ? "rotate-180" : ""
          }`}
        />
      </button>
      <div
        className={`grid transition-all duration-300 ease-in-out ${
          isOpen ? "grid-rows-[1fr] opacity-100 pb-6" : "grid-rows-[0fr] opacity-0"
        }`}
      >
        <div className="overflow-hidden">
          <p className="text-navy-200 text-base leading-relaxed font-sans">{a}</p>
        </div>
      </div>
    </div>
  );
}

function FAQSection() {
  return (
    <section className="bg-navy-950 py-24 relative overflow-hidden">
      <div className="absolute inset-0 grid-pattern opacity-30" />
      <div className="relative max-w-4xl mx-auto px-6">
        <Reveal className="text-center mb-16">
          <SectionLabel center>FAQ</SectionLabel>
          <h2 className="font-serif text-[32px] md:text-[44px] text-white mt-4">
            Frequently Asked Questions
          </h2>
        </Reveal>
        <Reveal>
          <div className="w-full divide-y divide-white/10">
            {faqs.map((f, i) => (
               <FAQAccordionItem key={i} q={f.q} a={f.a} />
            ))}
          </div>
        </Reveal>
      </div>
    </section>
  );
}

/* ---------- SECTION 9: RELATED SERVICES ---------- */
function RelatedServices() {
  const services = [
    {
      title: "Corporate Tax Return",
      path: "/pakistan-services/company-tax-return",
      desc: "Annual tax return filing for your corporate entity.",
    },
    {
      title: "SECP Annual Filing",
      path: "/pakistan-services/secp-annual-filing",
      desc: "Ensure your SECP forms (Form A, Form 29) are filed correctly.",
    },
    {
      title: "Sales Tax Registration",
      path: "/pakistan-services/sales-tax-registration",
      desc: "Register for Provincial Sales Tax (PRA/SRB) or Federal Sales Tax.",
    },
  ];

  return (
    <section className="bg-white py-24 border-t border-border">
      <div className="max-w-6xl mx-auto px-6">
        <Reveal className="text-center mb-14">
          <SectionLabel center>INTERNAL RESOURCES</SectionLabel>
          <h2 className="font-serif text-[32px] md:text-[44px] text-dark-text mt-4">
            Related Compliance Services
          </h2>
        </Reveal>
        <div className="grid md:grid-cols-3 gap-8">
          {services.map((s) => (
            <Reveal key={s.title}>
              <div className="border border-border p-6 rounded-xl bg-white flex flex-col justify-between h-full">
                <div>
                  <h3 className="font-sans font-semibold text-lg text-dark-text">{s.title}</h3>
                  <p className="mt-2 text-sm text-gray-600 leading-relaxed">{s.desc}</p>
                </div>
                <Link
                  to={s.path}
                  className="mt-6 inline-flex items-center gap-1.5 text-gold-500 font-semibold text-xs uppercase tracking-widest hover:gap-2.5 transition-all"
                >
                  View Service Details <ArrowRight size={12} />
                </Link>
              </div>
            </Reveal>
          ))}
        </div>
      </div>
    </section>
  );
}

/* ---------- SECTION 10: CTA BANNER ---------- */
function CTABannerCustom() {
  return (
    <section className="relative bg-navy-950 py-28 overflow-hidden text-center">
      <div className="absolute inset-0 diagonal-pattern opacity-100" />
      <div className="relative max-w-4xl mx-auto px-6 flex flex-col items-center">
        <Reveal>
          <p className="text-gold-500 uppercase text-xs font-semibold tracking-[0.15em]">
            OUTSOURCE YOUR COMPLIANCE
          </p>
          <h2 className="font-serif text-white text-[36px] md:text-[52px] mt-4 leading-[1.1]">
            Avoid FBR Penalties.
            <br />
            Let Us Handle Deductions.
          </h2>
          <p className="mt-6 text-navy-200 text-base md:text-[18px] max-w-xl mx-auto leading-relaxed">
            Eliminate the risk of tax audits. We offer an affordable, fully managed withholding tax service so you can focus entirely on growing your business.
          </p>
          <div className="mt-10 flex flex-wrap justify-center gap-4">
            <Link
              to="/contact"
              className="btn-gold rounded-none uppercase tracking-widest px-8 py-4 font-semibold text-sm"
            >
              Start Monthly Retainer
            </Link>
            <a
              href="https://wa.me/923000925335"
              target="_blank"
              rel="noopener noreferrer"
              className="btn-outline-light rounded-none uppercase tracking-widest px-8 py-4 font-semibold text-sm"
            >
              WhatsApp Us
            </a>
          </div>
          <p className="mt-6 text-[13px] text-navy-200">
            Dedicated Tax Experts · Fast PSIDs · Complete Record Keeping
          </p>
        </Reveal>
      </div>
    </section>
  );
}

/* ---------- PAGE ASSEMBLY ---------- */
export default function WithholdingCompliance() {
  return (
    <div className="page-transition">
      <Hero />
      <ServiceOverview />
      <TheDanger />
      <WhatIsIncluded />
      <Pricing />
      <ProcessSteps />
      <FAQSection />
      <RelatedServices />
      <CTABannerCustom />
    </div>
  );
}
